# Generated by Django 4.2.2 on 2023-06-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('sn', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(default=True, upload_to='parts/')),
                ('title', models.CharField(default=True, max_length=100)),
                ('content', models.CharField(default=True, max_length=500)),
                ('link', models.CharField(default=True, max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
