# Generated by Django 4.2.2 on 2023-06-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdcar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='content',
            field=models.CharField(default=True, max_length=180),
        ),
    ]
