# Generated by Django 4.2.2 on 2023-06-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdcar', '0002_alter_parts_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('name', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=150)),
                ('contact', models.IntegerField(default='', primary_key=True, serialize=False)),
                ('topic', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='parts',
            name='content',
            field=models.CharField(default=True, max_length=500),
        ),
    ]
