# Generated by Django 5.2.6 on 2025-09-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdcar", "0003_contact_alter_parts_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="contact",
            name="contact",
            field=models.CharField(default="", max_length=15),
        ),
    ]
